### ISSUE TITLE
Vimfiler breaks encoding detection

### ISSUE THREAD

**Issue by ressu** [Shougo/vimfiler.vim#315] opened 2015-08-31 06:36 UTC
I'm using vimfiler through the NeoBundleRecipe feature and I've enabled the default browser feature:

    let g:vimfiler_as_default_explorer = 1

Now that I open files encoded with ISO-8859-15 encoding the vim encoding detection fails. I see all of the umlauts with their character codes like <C4> 

Removing vimfiler from bundles makes everything work again.

This has been reproduced with Ubuntu 15.04 and Vim 7.4

**Comment by Shougo** [comment] 2015-08-31 19:44
OK.  I will test it.
Please create minimal .vimrc less than 30 lines and upload reproduce ways from Vim starting.

**Comment by ressu** [comment] 2015-09-16 06:40
Wow, that turned out to be a pain to reproduce with a small vimrc. Turns out that the issue isn't with the default explorer setting.

Here is the minimal vimrc https://gist.github.com/ressu/2d5d43163e738bf6e1bb

There is nothing more there than the inclusion of vimfiler. The issue itself presents when you create a file with a colon in the path:
```
mkdir /tmp/t:t
echo äöäö | iconv -t iso8859-1 > /tmp/t:t/doc.txt
vim -u /tmp/vimrc-debug.vim /tmp/t:t/doc.txt
```

That will cause the encoding detection to fail and the file encoding to be detected incorrectly

**Comment by Shougo** [comment] 2015-09-17 13:14
```vim
set nocompatible
set runtimepath+=~/work/vimfiler.vim
set runtimepath+=~/work/unite.vim

let g:vimfiler_as_default_explorer = 1

filetype plugin indent on
```

I cannot reproduce the problem.
Because, Vim cannot detect correct encoding with/without vimfiler.
I think it is not vimfiler problem.

**Comment by ressu** [comment] 2015-09-17 13:57
Hmm.. I wonder what the difference is. I can reproduce the effect by simply commenting and uncommenting line 2 in your example configuration. Also, the default_explorer option isn't really the problem here and it has no effect on the behavior, I was initially mistaken on that.

I'll try and reproduce this on something else than Ubuntu, I'll need to install a virtual machine for that though.

**Comment by ressu** [comment] 2015-11-03 10:20
OK, took me a while, but I just verified the problem with an alpine based vim installation. So it doesn't look like it's Ubuntu specific.

**Comment by Shougo** [comment] 2015-12-14 22:45
It is not vimfiler problem.
Closing.

**Closed by Shougo** 2015-12-14 22:45 UTC

**Comment by ressu** [comment] 2015-12-15 07:22
I can confirm that PR#343 resolves this issue.

**Comment by wsdjeg** [comment] 2015-12-15 07:33
i am using ubuntu ,and reproduce the problem,by the way my os is ubuntu 15.10,sa i know 15.04 has a lot of encoding bug,for example can not use chinese in mysql,i can confirm that is not due to encoding and local evn

**Comment by Shougo** [comment] 2015-12-15 12:16
Hm... I don't know why #343 occur this problem.
I cannot reproduce it.

**Comment by ressu** [comment] 2015-12-16 11:07
#343 talks about a problem with a semicolon and this issue is caused by the semicolon. So because #343 disables some features that break when a semicolon is present in the filepath, it removes this problem as well.

**Comment by Shougo** [comment] 2015-12-17 10:54
Oh, I get it.
It is vimfiler problem.  Thanks.
