### ISSUE TITLE
Vimfiler ordering in navigation pane

### ISSUE THREAD

**Issue by williamsbdev** [Shougo/vimfiler.vim#432] opened 2020-07-13 01:52 UTC
@Shougo - Thank you so much for this plugin!

I am trying to fix an issue I'm having but I need some help as I'm new to Vimscript.

It appears that in nested directories that the files are not alphabetically order (notice `tmux.sh` and `python.sh` should be in the reverse order):

![image](https://user-images.githubusercontent.com/2402655/87262795-dc5a8800-c480-11ea-9ba9-3f838ebe2803.png)

Here is another example where the `.ambassador/` is at the bottom of the directories and then the `.dockerignore` is at the bottom of the files in the navigation pane:

![image](https://user-images.githubusercontent.com/2402655/87262849-0f048080-c481-11ea-9cc3-d5235c92a7a3.png)

It seems that it's having issues with nested folders, `.directories`, and `.dotfiles`. This happened today after I updated both tmux and vim on my machine.

I want to help fix this and submit a PR back to this repo but I'm having a hard time understanding where to start and how to debug this. I noticed there was a test file and if I can write a test to replicate this, maybe that will help me.

Do you have some quick tips to get me going for debugging/troubleshooting and where this problem might be and the code I should be focusing on?

**Comment by Shougo** [comment] 2020-07-13 01:57
@williamsbdev I have tested it and it works for me.
The problem must be reproduce-able for everyone.
So you need to upload sample repository to reproduce and minimal vimrc.

If not, I just close the issue.  I don't have time to cannot reproduce.

**Comment by Shougo** [comment] 2020-07-13 01:59
The reproduce-able issue is like this.
https://github.com/Shougo/deoplete.nvim/issues/1114

Please compare with yours.

**Comment by Shougo** [comment] 2020-07-13 02:00
I think you have changed vimfiler sort order.

**Comment by Shougo** [comment] 2020-07-13 02:02
Ah, it is only reproduce-able in Vim8.
I will investigate the reason.

**Comment by Shougo** [comment] 2020-07-13 02:06
I get the reason.  It is because from Vim8's if_lua incompatibility.
I will fix it later.

**Comment by williamsbdev** [comment] 2020-07-13 02:16
@Shougo - Thanks for the super fast response!

I am happy to help work on this but as I'm new, I'd need a little guidance.

**Comment by Shougo** [comment] 2020-07-13 04:25
Fixed

**Closed** 2020-07-13 04:25 UTC

**Comment by williamsbdev** [comment] 2020-07-13 21:40
@Shougo - this worked great! Thank you so much for the quick resolution.
